# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-10 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='text',
            field=models.CharField(default='ddd', max_length=200),
            preserve_default=False,
        ),
    ]
