# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-11 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0002_thing_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thing',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
