# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0005_auto_20171126_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='today',
            field=models.BooleanField(default=True),
        ),
    ]
