# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0006_thing_today'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thing',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='thing',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
